### ISSUE TITLE
DESIGN to incorporate recency (e.g. past 7ds)

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#127]
As a user, I want to see the most recent articles, so that I can stay up to date with what's going on in my neighborhood. 

KPI: Engagement, conversion rate, click-through rate

**Comment by kw496** [comment]
Included three explorations in [Figma](https://www.figma.com/file/Ue1fW14sa8dNi63Zc1rGrf/Allied-Voices?node-id=1768%3A1630)

**Comment by kw496** [comment]
From 0 to 23 hours, instead of date, calculate the number of hours from current time.
For example, instead of `8/10/21`, say `2 hours ago`. 

From 1 to 10 days, instead of date, calculate the number of days from current day.
For example, instead of `8/2/21`, say `8 days ago`. 

From 11 days and onwards, show the date.

**Comment by kw496** [comment]
Design decision: Continue with current design, with the above change 👆
