### ISSUE TITLE
Search bar for location doesn't work

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#142]
![Screen Shot 2021-07-12 at 8.28.24 PM.png](https://images.zenhubusercontent.com/5f1f9af5f2b598456a4627b1/e6f492d4-c2a6-4238-8e48-859d827b7bfe)

**Comment by banhpete** [comment]
This actually might be because the google API isn't working anymore (we were using a free account), will need to look into this.

**Comment by banhpete** [comment]
Looked into it, so the issue is in regard to geocoder.js which uses Google's geocode API.

The API Key used is now invalid. For this to work we need to look into how we can renew the Google's geocode API Key.

As a side note, this should also be created into a netlify function so that we can hide the API key in Netlify's environment.
