### ISSUE TITLE
Picture doesn't change sometimes when going from article to article

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#70]
![1](https://user-images.githubusercontent.com/53403068/118306552-3536ea80-b4af-11eb-865a-cf96712fa795.png)
![2](https://user-images.githubusercontent.com/53403068/118306565-37994480-b4af-11eb-8405-78914926c708.png)

**Comment by banhpete** [comment]
@SDC-LZC Was taking a look at this, it turns out that images do change, but it requires time for the new image to load.

To create a better user experience, I've created an image loading state so that when we switch articles we're not just sitting there with the old image. 

See PR https://github.com/Allied-Voices/alliedvoices/pull/85
